### ISSUE TITLE
Fall back to global 'ops.yaml' when no action found

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/crops#14]
If the current directory `./ops.yaml` does not have the action to run, fall back to a 'global' `~/.ops.yaml` file (path configurable). Actions in this file should be prioritized over built-ins, except perhaps `init` when no current directory `./ops.yaml` exists (potentially configurable).

#### Example 1

1. Current directory `./ops.yaml` exists and has an `apply` action.
2. Global `~/.ops.yaml` has an `apply` action.
3. User runs `ops apply` and the action in working directory `./ops.yaml` is run.

#### Example 2

1. Current direcotry `./ops.yaml` exists but has no `apply` action.
2. Global `~/.ops.yaml` has an `apply` action.
3. User runs `ops apply` and the action in global `~/ops.yaml` is run.

#### Example 3

1. Current directory `./ops.yaml` does not exist.
2. Global `~/ops.yaml` has an `apply` action.
3. User runs `ops apply` and the action in global `~/ops.yaml` is run.

#### Example 4

1. Current directory `./ops.yaml` **doesn't** exist.
2. Global `~/.ops.yaml` has an `init` action.
3. User runs `ops init`. Current directory `./ops.yaml` is created. No action in global `~/.ops.yaml` is run.
4. Current directory `./ops.yaml` exists but has no `init` action.
5. User runs `ops init` and the action in global `~/.ops.yaml`is run.

#### Example 5

1. Current directory `./ops.yaml` but has no `init` action.
2. Global `~/.ops.yaml` has an `init` action.
3. User runs `ops init` and the action in global `~/.ops.yaml` is run.

#### Edge cases

Should still work when current directory `./ops.yaml` and global `~/.ops.yaml` are the same file.

**Comment by nickthecook** [comment]
There are a couple of principles that have been built into `ops` since the beginning that I think this would break:

1. you always know where to find the code for the action you ran in a given directory
2. all devs get the same behaviour from `ops` when they pull a repo with an `ops.yml`

I can see the feature you describe being helpful, but there are many ways to get this functionality on a Unix system, and I don't feel it should be built into `ops`.
